"""Checks the Python layer against values from the original catch22 C code.

The fixture is generated by `tools/make_fixtures.py`; see `docs/parity.md` for
what was compared and at what tolerance.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pytest

import pycatch22_rs

FIXTURE = Path(__file__).parent / "data" / "golden.tsv"

# Features that are integers or ratios of small integers, and so must match C
# exactly rather than to a tolerance.
EXACT_FEATURES = {6, 11, 13, 14, 16, 17, 21}
RTOL = 1e-9
ATOL = 1e-12


def load_fixture() -> list[tuple[str, np.ndarray, np.ndarray]]:
    cases = []
    with FIXTURE.open() as handle:
        for line in handle:
            if line.startswith("#") or not line.strip():
                continue
            fields = line.rstrip("\n").split("\t")
            name = fields[0]
            length = int(fields[1])
            expected = np.array([float(v) for v in fields[2 : 2 + 25]])
            series = np.array([float(v) for v in fields[2 + 25 : 2 + 25 + length]])
            assert len(series) == length, name
            cases.append((name, series, expected))
    assert cases, "golden fixture is empty"
    return cases


FIXTURES = load_fixture()
IDS = [name for name, _, _ in FIXTURES]


def agrees(actual: float, expected: float, exact: bool) -> bool:
    if np.isnan(actual) and np.isnan(expected):
        return True
    if actual == expected:
        return True
    if np.isnan(actual) != np.isnan(expected):
        return False
    if exact:
        return False
    return abs(actual - expected) <= ATOL + RTOL * abs(expected)


@pytest.mark.parametrize("name,series,expected", FIXTURES, ids=IDS)
def test_compute_all_matches_c(name, series, expected):
    actual = pycatch22_rs.compute_all(series, normalize=True)

    mismatches = [
        f"{pycatch22_rs.FEATURE_NAMES[i]}: got {actual[i]!r}, C gives {expected[i]!r}"
        for i in range(25)
        if not agrees(actual[i], expected[i], i in EXACT_FEATURES)
    ]
    assert not mismatches, f"{name}:\n" + "\n".join(mismatches)


def test_batch_matches_c():
    """Same check through the parallel batch path, for the equal-length subset."""
    by_length: dict[int, list[tuple[np.ndarray, np.ndarray]]] = {}
    for _, series, expected in FIXTURES:
        by_length.setdefault(len(series), []).append((series, expected))

    # Pick the most common length so the batch is actually exercised.
    length = max(by_length, key=lambda k: len(by_length[k]))
    group = by_length[length]

    batch = np.array([series for series, _ in group])
    expected = np.array([values for _, values in group])
    actual = pycatch22_rs.compute_batch(batch, normalize=True)

    for row in range(len(group)):
        for feature in range(25):
            assert agrees(
                actual[row, feature],
                expected[row, feature],
                feature in EXACT_FEATURES,
            ), f"row {row} feature {pycatch22_rs.FEATURE_NAMES[feature]}"
