//! Checks every feature against values produced by the original catch22 C
//! implementation.
//!
//! The fixture in `tests/data/golden.tsv` is generated by
//! `tools/make_fixtures.py` from the pinned C reference, so this runs anywhere
//! without the UCR archive or a C toolchain. `tools/ucr_check` is the wider
//! gate: it compares all 191,158 series in the archive.
// Feature indices are identities here, not cursors: `FEATURES[i]` and
// `FEATURE_NAMES[i]` must line up, so the loops index deliberately.
#![allow(clippy::needless_range_loop)]

use std::path::PathBuf;

const N: usize = catch22::N_CATCH22;

/// Features that are integers or ratios of small integers, and so must match
/// C exactly rather than to a tolerance.
const EXACT_FEATURES: &[usize] = &[6, 11, 13, 14, 16, 17, 21];

const RTOL: f64 = 1e-9;
const ATOL: f64 = 1e-12;

struct Fixture {
    name: String,
    expected: [f64; N],
    series: Vec<f64>,
}

fn load_fixtures() -> Vec<Fixture> {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../tests/data/golden.tsv")
        .canonicalize()
        .expect("golden fixture missing; regenerate with tools/make_fixtures.py");

    let text = std::fs::read_to_string(&path).expect("reading golden fixture");
    let mut fixtures = Vec::new();

    for line in text.lines() {
        if line.starts_with('#') || line.trim().is_empty() {
            continue;
        }
        let fields: Vec<&str> = line.split('\t').collect();
        let name = fields[0].to_string();
        let len: usize = fields[1].parse().expect("fixture length");

        let mut expected = [0.0; N];
        for (i, slot) in expected.iter_mut().enumerate() {
            *slot = fields[2 + i].parse().expect("fixture value");
        }

        let series: Vec<f64> = fields[2 + N..2 + N + len]
            .iter()
            .map(|token| token.parse().expect("fixture sample"))
            .collect();
        assert_eq!(series.len(), len, "{name}: truncated series");

        fixtures.push(Fixture {
            name,
            expected,
            series,
        });
    }

    assert!(!fixtures.is_empty(), "golden fixture is empty");
    fixtures
}

fn agrees(actual: f64, expected: f64, exact: bool) -> bool {
    if actual.is_nan() && expected.is_nan() {
        return true;
    }
    if actual == expected {
        return true;
    }
    if actual.is_nan() != expected.is_nan() {
        return false;
    }
    if exact {
        return false;
    }
    (actual - expected).abs() <= ATOL + RTOL * expected.abs()
}

#[test]
fn compute_all_normalized_matches_c() {
    let fixtures = load_fixtures();
    let mut failures = Vec::new();

    for fixture in &fixtures {
        let actual = catch22::compute_all_normalized(&fixture.series)
            .unwrap_or_else(|err| panic!("{}: {err}", fixture.name));

        for feature in 0..N {
            let exact = EXACT_FEATURES.contains(&feature);
            if !agrees(actual[feature], fixture.expected[feature], exact) {
                failures.push(format!(
                    "{} feature {} ({}): got {:.17e}, C gives {:.17e}",
                    fixture.name,
                    feature,
                    catch22::FEATURE_NAMES[feature],
                    actual[feature],
                    fixture.expected[feature],
                ));
            }
        }
    }

    assert!(
        failures.is_empty(),
        "{} mismatch(es) against the C reference:\n{}",
        failures.len(),
        failures.join("\n")
    );
}

/// The individually callable entry points must agree with the batched path.
/// They take different routes internally: `compute_all` shares one
/// autocorrelation across features 4, 5, 6, 9 and 20, while the named functions
/// each compute their own.
#[test]
fn named_features_match_c() {
    let fixtures = load_fixtures();
    let mut failures = Vec::new();

    for fixture in &fixtures {
        let z = catch22::zscore(&fixture.series);

        for feature in 0..N {
            let input: &[f64] = if feature < catch22::N_NORMALIZED {
                &z
            } else {
                &fixture.series
            };
            let actual = catch22::FEATURES[feature](input);
            let exact = EXACT_FEATURES.contains(&feature);

            if !agrees(actual, fixture.expected[feature], exact) {
                failures.push(format!(
                    "{} feature {} ({}): got {:.17e}, C gives {:.17e}",
                    fixture.name,
                    feature,
                    catch22::FEATURE_NAMES[feature],
                    actual,
                    fixture.expected[feature],
                ));
            }
        }
    }

    assert!(
        failures.is_empty(),
        "{} mismatch(es) against the C reference:\n{}",
        failures.len(),
        failures.join("\n")
    );
}
