from typing import Any, Sequence, TypedDict

import numpy as np
from numpy.typing import NDArray

FEATURE_NAMES: tuple[str, ...]
N_FEATURES: int
N_NORMALIZED: int
__version__: str

_Series = Sequence[float] | NDArray[Any]
_Batch = Sequence[Sequence[float]] | NDArray[Any]

class Catch22Result(TypedDict):
    names: list[str]
    values: list[float]

def compute_all(x: _Series, *, normalize: bool = ...) -> NDArray[np.float64]: ...
def compute_batch(x: _Batch, *, normalize: bool = ...) -> NDArray[np.float64]: ...
def compute(x: _Series, n: int, *, normalize: bool = ...) -> float: ...
def zscore(x: _Series) -> NDArray[np.float64]: ...
def catch22_all(data: _Series, catch24: bool = ...) -> Catch22Result: ...

# The 25 features, in FEATURE_NAMES order. Each takes the series as given and
# performs no normalisation.
def DN_OutlierInclude_n_001_mdrmd(x: _Series, *, normalize: bool = ...) -> float: ...
def DN_OutlierInclude_p_001_mdrmd(x: _Series, *, normalize: bool = ...) -> float: ...
def DN_HistogramMode_5(x: _Series, *, normalize: bool = ...) -> float: ...
def DN_HistogramMode_10(x: _Series, *, normalize: bool = ...) -> float: ...
def CO_Embed2_Dist_tau_d_expfit_meandiff(x: _Series, *, normalize: bool = ...) -> float: ...
def CO_f1ecac(x: _Series, *, normalize: bool = ...) -> float: ...
def CO_FirstMin_ac(x: _Series, *, normalize: bool = ...) -> float: ...
def CO_HistogramAMI_even_2_5(x: _Series, *, normalize: bool = ...) -> float: ...
def CO_trev_1_num(x: _Series, *, normalize: bool = ...) -> float: ...
def FC_LocalSimple_mean1_tauresrat(x: _Series, *, normalize: bool = ...) -> float: ...
def FC_LocalSimple_mean3_stderr(x: _Series, *, normalize: bool = ...) -> float: ...
def IN_AutoMutualInfoStats_40_gaussian_fmmi(x: _Series, *, normalize: bool = ...) -> float: ...
def MD_hrv_classic_pnn40(x: _Series, *, normalize: bool = ...) -> float: ...
def SB_BinaryStats_diff_longstretch0(x: _Series, *, normalize: bool = ...) -> float: ...
def SB_BinaryStats_mean_longstretch1(x: _Series, *, normalize: bool = ...) -> float: ...
def SB_MotifThree_quantile_hh(x: _Series, *, normalize: bool = ...) -> float: ...
def SC_FluctAnal_2_rsrangefit_50_1_logi_prop_r1(x: _Series, *, normalize: bool = ...) -> float: ...
def SC_FluctAnal_2_dfa_50_1_2_logi_prop_r1(x: _Series, *, normalize: bool = ...) -> float: ...
def SP_Summaries_welch_rect_area_5_1(x: _Series, *, normalize: bool = ...) -> float: ...
def SP_Summaries_welch_rect_centroid(x: _Series, *, normalize: bool = ...) -> float: ...
def SB_TransitionMatrix_3ac_sumdiagcov(x: _Series, *, normalize: bool = ...) -> float: ...
def PD_PeriodicityWang_th0_01(x: _Series, *, normalize: bool = ...) -> float: ...
def DN_Mean(x: _Series, *, normalize: bool = ...) -> float: ...
def DN_Spread_Std(x: _Series, *, normalize: bool = ...) -> float: ...
def SlopeOfLinearFit(x: _Series, *, normalize: bool = ...) -> float: ...
